apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mywebsite
  labels:
    app: mywebsite
spec:
  source:
    git:
      uri: "https://github.com/abhayachogale/FirstMicroservice"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: "DockerImage"
      name: "hub.docker.com/repository/docker/abhayachogale/mywebsite-11:latest"